import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from '@/components/providers/AuthProvider';
import { AlertProvider } from '@/components/providers/AlertProvider';
import { AccountProvider } from '@/contexts/AccountContext';
import Navbar from '@/components/layout/Navbar';
import AlertBadge from '@/components/alerts/AlertBadge';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AlertProvider>
            <AccountProvider>
              <div className="min-h-screen bg-gray-50">
                <Navbar />
                <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
                  {children}
                </main>
                <AlertBadge />
              </div>
            </AccountProvider>
          </AlertProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
